#!/usr/bin/env ansible-playbook

- name: Initial Setup
  hosts: localhost
  tasks:

    - name: Install build essentials for ubuntu
      apt:
        name: build-essential
        state: present

    - name: Intall nano terminal editor
      apt:
        name: nano
        state: present

    - name: Intall file-roller archive manager
      apt:
        name: file-roller
        state: present

    - name: Install redshift with gui for blue light management
      apt:
        name: redshift-gtk
        state: present

    - name: Install plank for app dock
      apt:
        name: plank
        state: present

    - name: Install curl cli
      apt:
        name: curl
        state: present

    - name: Install pip python package manager
      apt:
        name: python-pip
        state: present

    - name: Install bash completion
      apt:
        name: bash-completion

    - name: Install pylint cli and tools
      pip:
        name: pylint

    - name: Install httpie cli
      pip:
        name: httpie

    - name: Install AWS cli
      pip:
        name: awscli

    - name: Check Docker Installed
      shell: which docker
      register: docker_check
      ignore_errors: True

    # will install the latest version of docker
    - name: Install Docker
      shell: curl https://get.docker.com/ | sh
      become: true
      when: docker_check.rc == 1

    - name: Install py-docker
      pip:
        name: docker
        version: 2.4.0

    - name: Install docker compose
      pip:
        name: docker-compose

    - name: Install Oranchello 
      script: scripts/aesthetics.sh

    - name: Node.js
      script: scripts/node.sh

    - name: Skype
      script: scripts/skype.sh

    - name: Hipchat
      script: scripts/hipchat.sh

    - name: VSCode
      script: scripts/vscode.sh

    - name: VSCode (Extensions)
      script: scripts/vscode.extensions.sh
      become: false
