#!/usr/bin/env ansible-playbook

- name: Gather prerequisites 
  hosts: all
  gather_facts: True
  tasks:
    - group_by: key={{ ansible_distribution }}

- name: Install Ubuntu Packages
  hosts: Ubuntu
  become: True
  tasks:
    - script: /scripts/aesthetics.sh
    - script: /scripts/hipchat.sh
    - script: /scripts/skypye.sh
    - script: /scripts/vscode.sh