#!/usr/bin/env ansible-playbook

- name: Gather prerequisites
  hosts: all
  gather_facts: True
  tasks:
    - group_by: key={{ ansible_distribution }}

- name: Initial Setup
  hosts: localhost
  become: True
  tasks:

    - name: Install build essentials for ubuntu
      apt:
        name: build-essential
        state: present
      when: ansible_os_family == "Debian"

    - name: Intall nano terminal editor
      apt:
        name: nano
        state: present
      when: ansible_os_family == "Debian"

    - name: Install redshift with gui for blue light management
      apt:
        name: redshift-gtk
        state: present
      when: ansible_os_family == "Debian"

    - name: Install plank for app dock
      apt:
        name: plank
        state: present
      when: ansible_os_family == "Debian"

    - name: Install curl cli
      apt:
        name: curl
        state: present
      when: ansible_os_family == "Debian"

    - name: Install pip python package manager
      apt:
        name: python-pip
        state: present
      when: ansible_os_family == "Debian"

    - name: Install pylint cli and tools
      pip:
        name: pylint
      when: ansible_os_family == "Debian"

    - name: Install httpie cli
      pip:
        name: httpie
      when: ansible_os_family == "Debian"

    - name: Install AWS cli
      pip:
        name: awscli
      when: ansible_os_family == "Debian"

    - name: Install docker daemon and cli
      pip:
        name: docker
        version: 2.4.0
      when: ansible_os_family == "Debian"

    - name: Install docker compose
      pip:
        name: docker-compose
      when: ansible_os_family == "Debian"

    - name: Asesthetics
      script: scripts/aesthetics.sh
      when: ansible_os_family == "Debian"

    - name: Node.js
      script: scripts/node.sh
      when: ansible_os_family == "Debian"

    - name: Skype
      script: scripts/skype.sh
      when: ansible_os_family == "Debian"

    - name: Hipchat
      script: scripts/hipchat.sh
      when: ansible_os_family == "Debian"

    - name: VSCode
      script: scripts/vscode.sh
      when: ansible_os_family == "Debian"

    - name: VSCode (Extensions)
      script: scripts/vscode.extensions.sh
      become: false
      when: ansible_os_family == "Debian"
