- name: Check Teamviewer installed
  shell: which teamviewer
  register: teamviewer_check
  ignore_errors: True

- name: Install Teamviewer
  shell: |
    wget -O tv.deb https://download.teamviewer.com/download/teamviewer_i386.deb
    dpkg --install tv.deb
    rm -rf tv.deb
  when: teamviewer_check.rc == 1

- name: Check Slack installed
  shell: which slack
  register: slack_check
  ignore_errors: True

- name: Install Slack
  shell: |
    wget -O slack.deb https://downloads.slack-edge.com/linux_releases/slack-desktop-2.8.2-amd64.deb
    dpkg --install slack.deb
    rm -rf slack.deb
  when: slack_check.rc == 1

- name: Check Gitter installed
  shell: which gitter
  register: gitter_check
  ignore_errors: True

- name: Install Gitter
  shell: |
    wget -O gitter.deb https://update.gitter.im/linux64/gitter_3.1.0_amd64.deb
    dpkg --install gitter.deb
    rm -rf gitter.deb
  when: gitter_check.rc == 1
