- name: Check Skype installed
  shell: which skypeforlinux
  register: skype_check
  ignore_errors: True

- name: Install Skype
  shell: |
    wget -O skype.deb "https://repo.skype.com/latest/skypeforlinux-$(echo `getconf LONG_BIT`).deb"
    dpkg --install skype.deb
    rm -rf skype.deb
  when: skype_check.rc == 1

- name: Check Hipchat 4 installed
  shell: which hipchat4
  register: hipchat_check
  ignore_errors: True

- name: Install Hipchat 4
  shell: |
    sh -c 'echo "deb https://atlassian.artifactoryonline.com/atlassian/hipchat-  apt-client $(lsb_release -c -s) main" > /etc/apt/sources.list.d/atlassian-hipchat4.list'
    wget -O - https://atlassian.artifactoryonline.com/atlassian/api/gpg/key/public | sudo apt-key add -
    apt-get update
    apt-get install hipchat4
  when: hipchat_check.rc == 1