- name: Check if ssh key exists
  stat:
    path: "{{ssh_directory}}/git"
  register: git_ssh_key_exists

- name: Generate ssh key for git
  shell: |
    ssh-keygen -t rsa -C "{{git_ssh_key_user}}" -f "{{ssh_directory}}/git" -N ''
  become: False
  when: git_ssh_key_exists.stat.exists == False

- name: Install pylint cli and tools
  pip:
    name: pylint
    state: present

- name: Install httpie cli
  pip:
    name: httpie
    state: present

- name: Install AWS cli
  pip:
    name: awscli
    version: 1.11.130
    state: present

- name: Check Docker Installed
  shell: which docker
  register: docker_check
  ignore_errors: True

# will install the latest version of docker
- name: Install Docker
  shell: curl https://get.docker.com/ | sh
  when: docker_check.rc == 1

# https://github.com/ansible/ansible/issues/20492#issuecomment-274081101
- name: Install docker compose
  pip:
    name: docker-compose
    version: 1.9.0
    state: present

- name: Install Twine
  pip:
    name: twine
    state: present

- name: Install n node.js version manager
  npm:
    name: n
    global: yes
    state: present

- name: Install node.js 6 stable
  shell: n 6.9.2

- name: Install coffee-script
  npm:
    name: coffee-script
    global: yes
    state: present

- name: Install webpack
  npm:
    name: webpack
    version: '2.2.0'
    global: yes
    state: present

- name: Install ruby
  apt:
    name: ruby
    state: present

- name: Install travis-cli
  gem:
    name: travis-cli
    state: present

- name: Install ruby development tools
  apt:
    name: ruby-dev
    state: present

# check if vscode installed
- name: Check VSCode Installed
  shell: which code
  register: code_check
  ignore_errors: True

# will install the latest version of vscode
- name: Install Code
  shell: |
    wget -O code.deb https://go.microsoft.com/fwlink/?LinkID=760868
    dpkg --install code.deb
    rm -rf code.deb
  when: code_check.rc == 1
  notify: Install Code extensions
